"""alembic 비동기 env. DATABASE_URL은 app.config에서 읽고, 메타데이터는 app.models에서 가져온다."""
import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy.ext.asyncio import async_engine_from_config
from sqlalchemy.engine import Connection
from sqlalchemy import pool

from app.config import get_settings
from app.db import Base
import app.models  # noqa: F401  모델을 metadata에 등록

config = context.config
if config.config_file_name is not None:
    # disable_existing_loggers 기본값(True)은 앱 로거("c207.*")를 통째로 꺼 버린다.
    # 시험이 마이그레이션을 돌린 뒤 caplog 기반 케이스가 빈손이 되는 뿌리였다(2026-08-01 실측).
    fileConfig(config.config_file_name, disable_existing_loggers=False)

config.set_main_option("sqlalchemy.url", get_settings().database_url)
target_metadata = Base.metadata


# autogenerate 비교 옵션. 기본값이 꺼짐이라 server_default가 갈려도 후보에 안 잡힌다 —
# `is_active`·`credit_state`처럼 DB 기본값에 기대는 칸이 여럿이라(models.py) 모델만 고치고
# 마이그레이션은 비어 나오는 사고가 조용히 난다. 실제 반영은 여전히 손으로 확인한다
# (autogenerate 결과는 `# ### commands auto generated by Alembic - please adjust! ###`다).
# ⚠ 비교 옵션은 autogenerate에만 먹는다. upgrade·downgrade 거동은 안 바뀐다.
COMPARE_OPTS = {"compare_server_default": True}


def run_migrations_offline() -> None:
    context.configure(
        url=get_settings().database_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        **COMPARE_OPTS,
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection, target_metadata=target_metadata, **COMPARE_OPTS
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
