"""S15P11C207-80 initial schema

Revision ID: bd476bba124d
Revises:
Create Date: 2026-07-24 13:50:49.643891
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'bd476bba124d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gate_pass_event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('gate_no', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('beam_a_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('beam_b_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('matched_tagging_event_id', sa.BigInteger(), nullable=True),
    sa.Column('verdict', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gate_pass_event_event_id'), 'gate_pass_event', ['event_id'], unique=True)
    op.create_table('kiosk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('robot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=True),
    sa.Column('battery', sa.Integer(), nullable=True),
    sa.Column('network_status', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shuttle_arrival',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('gate_no', sa.Integer(), nullable=True),
    sa.Column('shuttle_no', sa.String(length=32), nullable=True),
    sa.Column('signal_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notified_robot_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shuttle_arrival_event_id'), 'shuttle_arrival', ['event_id'], unique=True)
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sticker_inspection',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tagging_event_id', sa.BigInteger(), nullable=True),
    sa.Column('attached', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('image_ref', sa.Text(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tagging_event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('gate_no', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('credit_state', sa.String(length=16), server_default='issued', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_by_pass_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tagging_event_event_id'), 'tagging_event', ['event_id'], unique=True)
    op.create_index(op.f('ix_tagging_event_tag_id'), 'tagging_event', ['tag_id'], unique=False)
    op.create_table('temporary_pass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_no', sa.String(length=32), nullable=True),
    sa.Column('kiosk_id', sa.Integer(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('ack', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('robot_status_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('robot_id', sa.Integer(), nullable=False),
    sa.Column('imu', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('odom', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comm_status', sa.String(length=32), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['robot_id'], ['robot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('robot_status_log')
    op.drop_table('alert')
    op.drop_table('temporary_pass')
    op.drop_index(op.f('ix_tagging_event_tag_id'), table_name='tagging_event')
    op.drop_index(op.f('ix_tagging_event_event_id'), table_name='tagging_event')
    op.drop_table('tagging_event')
    op.drop_table('sticker_inspection')
    op.drop_table('staff')
    op.drop_index(op.f('ix_shuttle_arrival_event_id'), table_name='shuttle_arrival')
    op.drop_table('shuttle_arrival')
    op.drop_table('robot')
    op.drop_table('kiosk')
    op.drop_index(op.f('ix_gate_pass_event_event_id'), table_name='gate_pass_event')
    op.drop_table('gate_pass_event')
    # ### end Alembic commands ###
